/**
 * embed-assets.js
 * Run AFTER building the client: node embed-assets.js
 * Reads every file in client/dist/ and bakes them into embedded-assets.js
 * as base64 strings so the pkg exe needs no companion files.
 */
const fs   = require('fs');
const path = require('path');

const DIST_DIR = path.join(__dirname, 'client', 'dist');
const OUT_FILE = path.join(__dirname, 'embedded-assets.js');

const assets = {};

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full);
    } else {
      // store as POSIX path from root e.g. "/assets/index-abc.js"
      const key = '/' + path.relative(DIST_DIR, full).replace(/\\/g, '/');
      assets[key] = fs.readFileSync(full).toString('base64');
    }
  }
}

console.log('📦 Embedding client/dist into embedded-assets.js ...');
walk(DIST_DIR);

const code = `// AUTO-GENERATED by embed-assets.js — do not edit manually.
// Regenerate with: node embed-assets.js
// Contains ${Object.keys(assets).length} files from client/dist/
module.exports = ${JSON.stringify(assets)};
`;

fs.writeFileSync(OUT_FILE, code, 'utf8');
const kb = Math.round(fs.statSync(OUT_FILE).size / 1024);
console.log(`✅ Done — embedded ${Object.keys(assets).length} files (${kb} KB) → embedded-assets.js`);
